In [141]:
from datetime import datetime, timedelta,date
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np


import chart_studio.plotly as py
import plotly.offline as pyoff
import plotly.graph_objs as go
from plotly.offline import iplot

import sklearn

from sklearn.model_selection import train_test_split


#import plotly.plotly as py





import cufflinks as cf
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)



In [3]:
import pandas as pd
import numpy as np
import missingno as msno
import seaborn as sns

from itertools import combinations
from collections import Counter
import collections
import itertools

#chart = sns.barplot(x="true_minute", y="num2", data = df3,  palette="GnBu_d")

chart.set_xticklabels(chart.get_xticklabels(), rotation=45)
chart.set_xlabel('\nTime',fontsize=30)
chart.set_ylabel('Transactions\n',fontsize=30)
chart.set_title('Transactions by minutes',fontsize=40)

chart.tick_params(labelsize=13)

NameError: name 'chart' is not defined

In [11]:
from datetime import datetime, timedelta,date
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from __future__ import division

import warnings
warnings.filterwarnings("ignore")

import plotly.plotly as py
import plotly.offline as pyoff
import plotly.graph_objs as go

#import Keras
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import Adam 
from keras.callbacks import EarlyStopping
from keras.utils import np_utils
from keras.layers import LSTM
from sklearn.model_selection import KFold, cross_val_score, train_test_split

#initiate plotly
pyoff.init_notebook_mode()



SyntaxError: from __future__ imports must occur at the beginning of the file (<ipython-input-11-0e00f8a3c1fe>, line 9)

In [4]:
data = pd.read_csv(r'C:\Users\MiPro\Desktop\_AnaliticaCourse_II\final_project\task_2.txt')

In [5]:
data

Дата  Число заказов
0   2020-01-05            650
1   2020-01-12            837
2   2020-01-19           1020
3   2020-01-26           1176
4   2020-02-02           1489
5   2020-02-09           1823
6   2020-02-16           1991
7   2020-02-23           2166
8   2020-03-01           2334
9   2020-03-08           2607
10  2020-03-15           2734
11  2020-03-22           3492
12  2020-03-29           3608
13  2020-04-05           3857

In [6]:
data = data.rename(columns = {'Дата':'date', 'Число заказов':'num'})

In [7]:
data

date   num
0   2020-01-05   650
1   2020-01-12   837
2   2020-01-19  1020
3   2020-01-26  1176
4   2020-02-02  1489
5   2020-02-09  1823
6   2020-02-16  1991
7   2020-02-23  2166
8   2020-03-01  2334
9   2020-03-08  2607
10  2020-03-15  2734
11  2020-03-22  3492
12  2020-03-29  3608
13  2020-04-05  3857

In [9]:
data['date'] = pd.to_datetime(data['date'])

In [10]:
data

date   num
0  2020-01-05   650
1  2020-01-12   837
2  2020-01-19  1020
3  2020-01-26  1176
4  2020-02-02  1489
5  2020-02-09  1823
6  2020-02-16  1991
7  2020-02-23  2166
8  2020-03-01  2334
9  2020-03-08  2607
10 2020-03-15  2734
11 2020-03-22  3492
12 2020-03-29  3608
13 2020-04-05  3857

In [20]:
#plot monthly sales
plot_data = [
    go.Scatter(
        x=data['date'],
        y=data['num'],
    )
]
plot_layout = go.Layout(
        title='Week Sales'
    )
fig = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig)

In [29]:
type(data['date'])

pandas.core.series.Series

In [23]:
df = data.set_index('date')

In [27]:
df.index

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16', '2020-02-23',
               '2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22',
               '2020-03-29', '2020-04-05'],
              dtype='datetime64[ns]', name='date', freq=None)

In [26]:
from sklearn import linear_model



X = (df.index -  df.index[0]).days.reshape(-1, 1)
y = df[''].num
linear_model.LinearRegression().fit(X, y)
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

AttributeError: 'Int64Index' object has no attribute 'reshape'

In [31]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [32]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [33]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [34]:
y

array([ 5, 20, 14, 32, 22, 38])

In [35]:
model = LinearRegression()

In [36]:
model = LinearRegression().fit(x, y)

In [38]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.715875613747954


In [39]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [40]:
x_new = np.arange(5).reshape((-1, 1))

y_new = model.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


In [45]:
x_new2 = [8, 10, 15]
x_new3 = np.array(x_new2).reshape((-1, 1))

In [46]:
y_new31 = model.predict(x_new3)
print(y_new31)

[ 9.95333333 11.03333333 13.73333333]


In [ ]:
#https://realpython.com/linear-regression-in-python/

In [103]:
x1 = np.array(data['num'])

In [104]:
x1

array([ 650,  837, 1020, 1176, 1489, 1823, 1991, 2166, 2334, 2607, 2734,
       3492, 3608, 3857], dtype=int64)

In [105]:
y1 = np.array([i for i in range(1,15)]).reshape((-1, 1))

In [106]:
y1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [107]:
model = LinearRegression().fit(y1, x1)

In [108]:
r_sq = model.score(y1, x1)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.9825538022955216


In [109]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 270.98901098901115
slope: [247.52527473]


In [110]:
y2 = np.array([i for i in range(16,19)]).reshape((-1, 1))

In [111]:
x2 = model.predict(y2)
print(x2)

[4231.39340659 4478.91868132 4726.44395604]


In [113]:
data['differ'] = data['num'].diff()

data['differ']

0       NaN
1     187.0
2     183.0
3     156.0
4     313.0
5     334.0
6     168.0
7     175.0
8     168.0
9     273.0
10    127.0
11    758.0
12    116.0
13    249.0
Name: differ, dtype: float64

In [114]:
data

date   num  differ
0  2020-01-05   650     NaN
1  2020-01-12   837   187.0
2  2020-01-19  1020   183.0
3  2020-01-26  1176   156.0
4  2020-02-02  1489   313.0
5  2020-02-09  1823   334.0
6  2020-02-16  1991   168.0
7  2020-02-23  2166   175.0
8  2020-03-01  2334   168.0
9  2020-03-08  2607   273.0
10 2020-03-15  2734   127.0
11 2020-03-22  3492   758.0
12 2020-03-29  3608   116.0
13 2020-04-05  3857   249.0

In [123]:
data['week_num'] = range(1, 15)

In [124]:
data

date   num  differ  week_num
0  2020-01-05   650     NaN         1
1  2020-01-12   837   187.0         2
2  2020-01-19  1020   183.0         3
3  2020-01-26  1176   156.0         4
4  2020-02-02  1489   313.0         5
5  2020-02-09  1823   334.0         6
6  2020-02-16  1991   168.0         7
7  2020-02-23  2166   175.0         8
8  2020-03-01  2334   168.0         9
9  2020-03-08  2607   273.0        10
10 2020-03-15  2734   127.0        11
11 2020-03-22  3492   758.0        12
12 2020-03-29  3608   116.0        13
13 2020-04-05  3857   249.0        14

In [128]:
data.columns

Index(['date', 'num', 'differ', 'week_num'], dtype='object')

In [115]:
#plot monthly sales
plot_data = [
    go.Scatter(
        x=data['date'],
        y=data['differ'],
    )
]
plot_layout = go.Layout(
        title='Week Sales Diff'
    )
fig2 = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig2)

In [ ]:
def make_prediction(label, prediction):
    X = df[[col1, col2, col3]].values
    y = df[label].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
    X_train.shape, X_test.shape
    clf = linear_model.LinearRegression()
    clf.fit(X_train, y_train)
    output = clf.predict(X)
    result = np.c_[X, output]
    df_result = pd.DataFrame(result, columns=[col1, col2, col3, prediction])
    return df_result

In [121]:
df['col1'] = range(1,15)

In [122]:
df

num  col1
date                  
2020-01-05   650     1
2020-01-12   837     2
2020-01-19  1020     3
2020-01-26  1176     4
2020-02-02  1489     5
2020-02-09  1823     6
2020-02-16  1991     7
2020-02-23  2166     8
2020-03-01  2334     9
2020-03-08  2607    10
2020-03-15  2734    11
2020-03-22  3492    12
2020-03-29  3608    13
2020-04-05  3857    14

In [144]:
data['diff2'] = data['differ'].fillna(0)

In [155]:
X = data[['num']].values

In [156]:
y = data['week_num'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X_train.shape, X_test.shape
clf = linear_model.LinearRegression()
clf.fit(X_train, y_train)
output = clf.predict(X)
result = np.c_[X, output]
#df_result = pd.DataFrame(result, columns=['diff2', 'week_num', 'num', 'prediction'])

In [157]:
print(result)

[[6.50000000e+02 1.64209249e+00]
 [8.37000000e+02 2.39757630e+00]
 [1.02000000e+03 3.13690003e+00]
 [1.17600000e+03 3.76714320e+00]
 [1.48900000e+03 5.03166958e+00]
 [1.82300000e+03 6.38103639e+00]
 [1.99100000e+03 7.05975981e+00]
 [2.16600000e+03 7.76676338e+00]
 [2.33400000e+03 8.44548680e+00]
 [2.60700000e+03 9.54841236e+00]
 [2.73400000e+03 1.00614950e+01]
 [3.49200000e+03 1.31238304e+01]
 [3.60800000e+03 1.35924728e+01]
 [3.85700000e+03 1.45984378e+01]]
